---
name: Node.js Package (next tag)

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - run: pnpm i
      - run: |
          npm version prerelease --no-git-tag-version \
            --preid=`git rev-parse --short HEAD`
          npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
